name: build - macos
on:
  workflow_call:

jobs:
  macos:
    strategy:
      matrix:
        config: [debug, release]
        compiler: [clang]
        arch: [x86, arm64]
        # Check https://github.com/actions/runner-images#available-images
        include:
          - arch: x86
            os: 12
          - arch: arm64
            os: 14
    name: MacOS ${{ matrix.config }} ${{ matrix.compiler }} ${{ matrix.arch }}
    runs-on: macos-${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Installing dependencies
      run: |
        export ICU_ROOT="$(brew --prefix icu4c)"
        # Suppress warnings about installing formulas instead of casks. Casks would raise another
        # warning about disabling macos gatekeeper.
        ./install-dependencies.sh homebrew --formula
        # temporary fix for macos-14 arm failures
        brew install --quiet icu4c
    - name: Building
      run: |
        mkdir build_wl
        cd build_wl/
        ../utils/macos/build_app.sh "--${{ matrix.config }}" "--${{ matrix.compiler }}"
        grep -v REVDETECT-BROKEN ../build/VERSION
        DMGPATH="$(pwd)"
        DMGFILE="$(ls *.dmg)"
        echo "DMG file is: $DMGPATH/$DMGFILE"
        mv "$DMGFILE" "${{ github.workspace }}/Widelands-${{ github.sha }}-${{ matrix.config }}-${{ matrix.compiler }}-${{ matrix.arch }}.dmg"

    - name: Uploading DMG
      uses: actions/upload-artifact@v4
      with:
        name: Widelands ${{ matrix.config }} ${{ matrix.compiler }} MacOS ${{ matrix.os }} ${{ matrix.arch }} AppImage
        path: ${{ github.workspace }}/Widelands-${{ github.sha }}-${{ matrix.config }}-${{ matrix.compiler }}-${{ matrix.arch }}.dmg
